### ISSUE TITLE
As an user, I want to pull my application image from a private container registry

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-operator#233]
When the statefulset is created, the container image must be pullable from the container platform.

Public images can be pulled without any issue.
On OpenShift, any image in the OpenShift image registry can be pulled.

But if my application image is in a private container registry, I don't have the ability to provide an imagePullSecret that would be used to pull my image when the pods are started.

To support this use case, the WildFlyServer CRD can be enhanced with a imagePullSecrets array that will be used to populate the pod template spec.imagePullSecrets field.

The use case would then be fulfilled with the CRD:

```
spec:
  applicationImage: quay.io/my-private-group/my-private-image
  imagePullSecrets:
    - name: my-private-pull-secret
```
